---
title: "junk"
output: html_notebook
---

```{r}

customers <- tibble(cid = unique(transactions$customer_id), duplicates = NA)
doubles <- NA


# for (variable in customers$cid) {
if (
transactions2 %>%
  filter(customer_id == "b6d0d3c61122345690a19bb8af632db4") %>%
  nrow() 

==

transactions2 %>%
  filter(customer_id == "b6d0d3c61122345690a19bb8af632db4") %>%
  filter(!duplicated(date)) %>%
  nrow()
) { 
 rbind(doubles, "FALSE")
} else { 
  rbind(doubles, "TRUE")
  }
```

```{r}
industries_and_plots <- data.frame(stringsAsFactors = FALSE)
for (indust in 1:10){
  dfname <- paste("transactions_industry", indust, sep = "_")
  plotname <- paste("plot_trans_industry", indust, sep = "_")
  dfind <- transactions %>%
    filter(industry == indust)
  plotind <- ggplot(dfind, aes(x=date , y= monthly_amount)) + geom_point(alpha = 0.25)
  assign(dfname, dfindust)
  assign(plotname, plotind)
  ind_row <- cbind(dfname, plotname)
  industries_and_plots <- rbind(industries_and_plots, ind_row)
}
```

```{r}
industries_and_plots <- data.frame(stringsAsFactors = FALSE)
plotlist_industry <- list()
for (indust in 1:10){
  dfname <- paste("transactions_industry", indust, sep = "_")
  plotname <- paste("plot_trans_industry", indust, sep = "_")
  dfind <- transactions %>%
    filter(industry == indust)
  plotind <- ggplot(dfind, aes(x=date , y= monthly_amount)) + geom_point(alpha = 0.25)
  assign(dfname, dfindust)
  assign(plotname, plotind)
  plotlist_industry[[indust]] <- plotname
}
```

